### ISSUE TITLE
Broken message ID.

### ISSUE THREAD

**Issue by pushkar-anand** [pushkar-anand/easy-mail#1]
The header  `Message-Id` generated by the mailer is reported broken in Gmail.

![screenshot from 2018-10-01 16-05-59](https://user-images.githubusercontent.com/13116715/46284030-f79e2100-c593-11e8-8136-da697171f021.png)

The ID is generated on line 275 and 276 in the file [Mail.php](https://github.com/pushkar-anand/easy-mail/blob/master/src/Mail.php).

**Comment by shubhodeep9** [comment]
I found a very helpful working gist: https://gist.github.com/Robbert/4967898

**Comment by manjutapali** [comment]
Message ID should be included in angular brackets.
composer require pushkar/simple-mailer this isn't working.

**Comment by pushkar-anand** [comment]
please make the necessary changes and send a pull request.

**Comment by manjutapali** [comment]
I forked your repo and there is an error while installing.
composer require pushkar/simple-mailer this isn't working.

 [InvalidArgumentException]                                                                                                                             
  Could not find package pushkar/simple-mailer at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by pushkar-anand** [comment]
My mistake the package is `pushkar/easy-mail` please use `composer require pushkar/easy-mail`

**Comment by manjutapali** [comment]
PR coming.
